project:
  type: website
  output-dir: docs
  resources:
    - "images/*.pdf"

website:
  title: "cbt-star.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - aboutme.qmd
      - projects.qmd
      - ecr.qmd
      - resume.qmd
format:
  html:
    theme:
      - journal
      - brand
    css: styles.css
    toc: true



