project:
  type: website
  output-dir: docs
  resources:
    - "images/*.pdf"

website:
  title: "Cassidy Thorpe"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - aboutme.qmd
      - projects.qmd
      - ecr.qmd
format:
  html:
    lightbox: true
    theme:
      - journal
      - styles.scss
    toc: true
    



